# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-12 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('url_title', models.CharField(default='', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'mathvisualized_category',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('js_lib', models.CharField(choices=[('c', 'HTML Canvas'), ('b', 'BonsaiJS'), ('t', 'Three.js'), ('k', 'Konva')], default='c', max_length=1)),
                ('title', models.CharField(default='', max_length=255)),
                ('url_title', models.CharField(default='', max_length=255, unique=True)),
                ('text', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'mathvisualized_page',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('url_title', models.CharField(default='', max_length=255, unique=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mathvisualized.Category')),
            ],
            options={
                'db_table': 'mathvisualized_subcategory',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mathvisualized.Subcategory'),
        ),
    ]
