# Generated by Django 2.0.2 on 2018-04-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathvisualized', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url_title',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.CharField(default='', max_length=256),
        ),
    ]
