# Generated by Django 2.0.2 on 2018-04-23 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathvisualized', '0002_auto_20180417_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_id', models.CharField(choices=[('c', 'HTML Canvas'), ('b', 'BonsaiJS'), ('t', 'Three.js')], default='c', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='js_lib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mathvisualized.JsLib'),
        ),
    ]
