# Generated by Django 2.0.2 on 2018-04-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathvisualized', '0003_auto_20180423_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='js_lib',
            field=models.CharField(choices=[('c', 'HTML Canvas'), ('b', 'BonsaiJS'), ('t', 'Three.js')], default='c', max_length=1),
        ),
        migrations.DeleteModel(
            name='JsLib',
        ),
    ]
