# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-06 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathvisualized', '0004_auto_20180423_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='js_lib',
            field=models.CharField(choices=[('c', 'HTML Canvas'), ('b', 'BonsaiJS'), ('t', 'Three.js'), ('k', 'Konva')], default='c', max_length=1),
        ),
    ]
